import { ROLES } from "./roles.js";

export const ACCESS = Object.freeze({
    ADMIN_AREA: [ROLES.SUPER_ADMIN, ROLES.INSTITUTE_ADMIN],
    SUPERADMIN_ONLY: [ROLES.SUPER_ADMIN],
    INSTITUTE_PORTAL: [ROLES.INSTITUTE_ADMIN, ROLES.FACULTY],
});
